name: Update gist with WakaTime stats
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js > "README.md"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 377ee88ba1fabd1e93516e48ca9c61eb
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-walle"
          git add -A
          git commit -m "Updated content" || exit 0
          git push
